// <auto-generated />
using System;
using CapstoneProject_MySoldiers_DanWay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapstoneProject_MySoldiers_DanWay.Migrations
{
    [DbContext(typeof(dbMySoldiersContext))]
    [Migration("20210810053523_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapstoneProject_MySoldiers_DanWay.TbSoldier", b =>
                {
                    b.Property<int>("SoldierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Soldier_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("date")
                        .HasColumnName("Add_Date");

                    b.Property<int?>("AddId")
                        .HasColumnType("int")
                        .HasColumnName("Add_ID");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("date")
                        .HasColumnName("Mod_Date");

                    b.Property<int?>("ModId")
                        .HasColumnType("int")
                        .HasColumnName("Mod_ID");

                    b.Property<string>("SoldierAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nchar(255)")
                        .HasColumnName("Soldier_Address")
                        .IsFixedLength(true);

                    b.Property<int>("SoldierAge")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Age");

                    b.Property<DateTime?>("SoldierAitEntryDate")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_AIT_Entry_Date");

                    b.Property<DateTime?>("SoldierAitGradDate")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_AIT_Grad_Date");

                    b.Property<int?>("SoldierAltMosId")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Alt_MOS_ID");

                    b.Property<DateTime?>("SoldierBasicEntryDate")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_Basic_Entry_Date");

                    b.Property<DateTime?>("SoldierBasicGradDate")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_Basic_Grad_Date");

                    b.Property<int?>("SoldierBloodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SoldierCity")
                        .HasMaxLength(255)
                        .HasColumnType("nchar(255)")
                        .HasColumnName("Soldier_City")
                        .IsFixedLength(true);

                    b.Property<string>("SoldierCurrRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Soldier_Curr_Rank");

                    b.Property<DateTime>("SoldierDob")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_DOB");

                    b.Property<DateTime?>("SoldierDor")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_DOR");

                    b.Property<DateTime?>("SoldierEts")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_ETS");

                    b.Property<string>("SoldierEyeColor")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Soldier_Eye_Color");

                    b.Property<string>("SoldierFname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("char(25)")
                        .HasColumnName("Soldier_FName")
                        .IsFixedLength(true);

                    b.Property<byte[]>("SoldierGender")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("Soldier_Gender");

                    b.Property<string>("SoldierHairColor")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Soldier_Hair_Color");

                    b.Property<int?>("SoldierHeight")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Height");

                    b.Property<string>("SoldierLname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("char(25)")
                        .HasColumnName("Soldier_LName")
                        .IsFixedLength(true);

                    b.Property<int?>("SoldierMaritalStatus")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Marital_Status");

                    b.Property<string>("SoldierMname")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("char(25)")
                        .HasColumnName("Soldier_MName")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("SoldierPebd")
                        .HasColumnType("date")
                        .HasColumnName("Soldier_PEBD");

                    b.Property<int?>("SoldierPriMos")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Pri_MOS");

                    b.Property<int?>("SoldierReligion")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Religion");

                    b.Property<string>("SoldierRole")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Soldier_Role");

                    b.Property<int?>("SoldierSecMos")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Sec_MOS");

                    b.Property<string>("SoldierSsn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Soldier_SSN");

                    b.Property<string>("SoldierState")
                        .HasMaxLength(255)
                        .HasColumnType("nchar(255)")
                        .HasColumnName("Soldier_State")
                        .IsFixedLength(true);

                    b.Property<string>("SoldierSuffix")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("char(25)")
                        .HasColumnName("Soldier_Suffix")
                        .IsFixedLength(true);

                    b.Property<int?>("SoldierTigMonths")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_TIG_Months");

                    b.Property<int?>("SoldierTigYears")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_TIG_Years");

                    b.Property<int?>("SoldierTisMonths")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_TIS_Months");

                    b.Property<int?>("SoldierTisYears")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_TIS_Years");

                    b.Property<int?>("SoldierWeight")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Weight");

                    b.Property<int?>("SoldierZip")
                        .HasColumnType("int")
                        .HasColumnName("Soldier_Zip");

                    b.HasKey("SoldierId")
                        .HasName("PK__tbSoldie__FC3C500295173598");

                    b.ToTable("tbSoldiers");
                });
#pragma warning restore 612, 618
        }
    }
}
